apiVersion: v1
kind: Secret
metadata:
  name: game-secrets
type: Opaque
stringData:
  # Kubernetes will base64 encode this automatically when applied
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USERNAME: gameuser
  DB_PASSWORD: ahmed123
  DB_DATABASE: killer_game
  DB_NAME: killer_game
  DB_USER: gameuser
  PORT: "3000"
  MYSQL_ROOT_PASSWORD: ahmed123
  SWAGGER_USER: admin
  SWAGGER_PASSWORD: admin123