# charts/social-game/values.yaml

replicaCount: 1

image:
  repository: ahmedbenrejeb0/backend
  tag: 234cef7177568495717be51d47112de0581a0c28
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: killer-game.local