apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #  Force SSL redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx

  tls:
  - hosts:
      - killer-game.local
    secretName: game-tls-secret

  rules:
  - host: killer-game.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend    
            port:
              number: 3000